method: bayes
metric:
  name: test_loss
  goal: minimize
parameters:
  cuda:
    values: [2]
  seed:
    values: [1]
  data:
    values: ['ISRUC_S3_10']
  fold:
    values: [2]
  num_epochs:
    values: [60]
  batch:
    values: [4, 8, 12, 16, 32, 64]
#    min: 4
#    max: 64
  lr:
#    values: [0.0005]
    values: [0.005, 0.001, 0.0005, 0.0001, 0.00005, 0.00001]
#    min: 0.000001
#    max: 0.001
  drop_n:
    values: [0.2, 0.3, 0.4, 0.5]
#    values:[0.3]
#    min: 0.1
#    max: 0.5
  drop_c:
    values: [0.2, 0.3, 0.4, 0.5]
#    values:[0.3]
#    min: 0.1
#    max: 0.5
  act_n:
    values: ['ELU']
#    values: ['ReLU', 'ELU', 'LeakyReLU']
  act_c:
    values: ['ELU']
#    values: ['ReLU', 'ELU', 'LeakyReLU']
  ks:
    values: ['0.9 0.8 0.7']
#    values: ['0.9 0.8 0.7', '0.8 0.7 0.6', '0.8 0.8 0.8', '0.7 0.8 0.6']
  cs:
    values: ['0.5 0.5 0.5']
#    values: ['0.5 0.5 0.5', '0.5 0.2 0.1', '0.5 0.2 0.2', '0.5 0.1 0.1', '0.2 0.2 0.2',
#             '0.2 0.5 0.5', '0.2 0.1 0.1', '0.5 0.25 0.25', '0.5 0.25 0.125']
  sch:
    values: [0, 1, 2]
  chs:
    # '8 16 32 64',
    values: ['16 32 64 128', '32 64 128 256', '64 128 256 512']
  kernal:
    values: [5, 7, 9, 12, 15]
  gcn_h:
    values: ['4096 2048 1024 512']
  l_n:
    values: [4]
  weightDecay:
    values: [0.005]
#    min: 0.0001
#    max: 0.001
  lrStepSize:
    values: [10]
#    values: [5, 10, 20]
  lrGamma:
    values: [0.1]
#    min: 0.05
#    max: 0.5
  lrFactor:
    values: [0.5]
#    min: 0.1
#    max: 0.9
  lrPatience:
    values: [5]
#    min: 2
#    max: 10
  wdb:
    values: [True]
  sweep:
    values: [True]
