method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  cuda:
    values: [1]
  seed:
    values: [1, 42, 56, 100]
  data:
    values: ['ISRUC_S3_10']
  fold:
    values: [1]
  num_epochs:
    values: [100]
  batch:
#    values: [4, 8, 12, 16, 32, 64]
    min: 4
    max: 64
  lr:
    min: 0.000001
    max: 0.001
  drop_n:
    min: 0.1
    max: 0.5
  drop_c:
    min: 0.1
    max: 0.5
  act_n:
    values: ['ReLU', 'ELU', 'LeakyReLU']
  act_c:
    values: ['ReLU', 'ELU', 'LeakyReLU']
  ks:
    values: ['0.9 0.8 0.7', '0.8 0.7 0.6', '0.8 0.8 0.8', '0.7 0.8 0.6']
  cs:
    values: ['0.5 0.5 0.5', '0.5 0.2 0.1', '0.5 0.2 0.2', '0.5 0.1 0.1', '0.2 0.2 0.2',
             '0.2 0.5 0.5', '0.2 0.1 0.1', '0.5 0.25 0.25', '0.5 0.25 0.125']
  sch:
    values: [0, 1, 2]
  chs:
    values: ['16 32 64 128', '8 16 32 64', '32 64 128 256', '64 128 256 512']
  kernal:
    values: [3, 5, 7, 9, 12, 15]
  weightDecay:
    min: 0.0001
    max: 0.001
  lrStepSize:
    values: [5, 10, 20]
  lrGamma:
    min: 0.05
    max: 0.5
  lrFactor:
    min: 0.1
    max: 0.9
  lrPatience:
    min: 2
    max: 10
  wdb:
    values: [True]
  sweep:
    values: [True]
